spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    hikari:
      maximum-pool-size: 2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 465
    username: buidinhhoang1910@gmail.com
    password: kiflurzibulqhzzy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:DEFAULT_SECRET}
            scope:
              - email
              - profile

jwt:
  secret: dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1nZW5lcmF0aW9uLXdpdGgtYXQta2Vhc3QtMjU2LWJpdHM=
  access-token:
    expiration: 3600000 # 1 hour
  refresh-token:
    expiration: 604800000 # 7 days

google:
  client-id: ${GOOGLE_CLIENT_ID:DEFAULT_ID}

app:
  frontend-url: ${APP_FRONTEND_URL:http://localhost:3000}

file:
  upload-dir: uploads

restaurant:
  network:
    cidr: 172.20.10.0/24

server:
  port: ${PORT:8081}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO

resend:
  api-key: ${RESEND_API_KEY:re_WhVHk8Vc_MccxCgbinesGVCXeXbvndt3s}
  from-email: ${RESEND_FROM_EMAIL:onboarding@resend.dev}
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:your_cloud_name_here}
  api-key: ${CLOUDINARY_API_KEY:your_api_key_here}
  api-secret: ${CLOUDINARY_API_SECRET:your_api_secret_here}
