spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SeftOrderingRestaurant
    username: root
    password: Dinhho@ng1910
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB